# Generated by Django 5.1.6 on 2025-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TourPackage",
            fields=[
                (
                    "product_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("airline", models.CharField(max_length=50)),
                ("airline_logo", models.CharField(max_length=100)),
                ("departure_days", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=20)),
                ("master_code", models.CharField(max_length=10)),
                ("product_no", models.CharField(max_length=20)),
                ("list_url", models.URLField()),
            ],
            options={
                "verbose_name": "Tour Package",
                "verbose_name_plural": "Tour Packages",
                "db_table": "tour_packages",
            },
        ),
    ]
